### ISSUE TITLE
sample_hmc error

### ISSUE THREAD

**Issue by bsierieb1** [theislab/scCODA#15]
this is a [duplicate](https://github.com/johannesostner/SCDCdm_public/issues/2) because i am not sure where to post issues.

hi,

i am trying to run scdcdm with a tiny fraction of my real data set as a test, and i am basically following the [tutorial](https://github.com/theislab/scCODA/blob/master/tutorials/Tutorial.ipynb).

however, i get the error message below, which i do not understand. i would appreciate any advice!

```
In [110]: import scdcdm

In [111]: from scdcdm.util import cell_composition_data as dat

In [112]: from scdcdm.util import comp_ana as mod

In [113]: dat_pandas
Out[113]: 
      0     1     2  condition
0  1065  1001  1232    control
1   439   435   197  treatment

In [114]: dat_scdcdm = dat.from_pandas(dat_pandas,
     ...:                              covariate_columns=["condition"])
Transforming to str index.

In [115]: dat_model = mod.CompositionalAnalysis(dat_scdcdm,
     ...:                                       formula="condition",
     ...:                                       baseline_index=None)

In [116]: sim_results = dat_model.sample_hmc()
WARNING:tensorflow:5 out of the last 5 calls to <function CompositionalModel.sampling.<locals>.sample_mcmc at 0x7f8fe4d5e8c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
MCMC sampling finished. (42.321 sec)
Acceptance rate: 35.0%
/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:376: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:576: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item_labels[indexer[info_axis]]] = value
Traceback (most recent call last):

  File "<ipython-input-116-4c85d20e3019>", line 1, in <module>
    sim_results = dat_model.sample_hmc()

  File "/Applications/python_modules/SCDCdm/SCDCdm_public/scdcdm/model/dirichlet_models.py", line 226, in sample_hmc
    model_specs=model_specs)

  File "/Applications/python_modules/SCDCdm/SCDCdm_public/scdcdm/util/result_classes.py", line 35, in to_result_data
    "observed_data": obs,

  File "/Applications/python_modules/SCDCdm/SCDCdm_public/scdcdm/util/result_classes.py", line 80, in __init__
    intercept_df, effect_df = self.summary_prepare()

  File "/Applications/python_modules/SCDCdm/SCDCdm_public/scdcdm/util/result_classes.py", line 134, in summary_prepare
    intercept_df = intercept_df.loc[:, ["final_parameter", hpds[0], hpds[1], "sd", "expected_sample"]]

  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4280, in __getitem__
    return getitem(key)

IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by bsierieb1** [comment]
i was not sure if the absence of replicates was an issue, so i re-ran it with modified data which included replicates and got the same error. the new data:
```
dat_pandas
Out[181]: 
      0     1     2  condition
0  1065  1001  1232    control
1   439   435   197  treatment
2  1072  1003  1232    control
3   439   500   197  treatment
4  1015  1001  1232    control
5   439   435   300  treatment
6  1065  1003  1232    control
7  1023  1100  1013  treatment

```

**Comment by b-schubert** [comment]
Dear @bsierieb1 have you tried the development branch? We made substantial changes to the code base (also due to changing APIs of dependencies) that have not yet made it to the master branch.

**Comment by bsierieb1** [comment]
ok, it worked, thanks!
